name: miio_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9

  ##Dependecy injection / Navigation
  flutter_modular: ^4.5.1+1

  #State Management
  flutter_bloc: ^8.0.1

  #Network/API
  dio: ^4.0.6

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  # Unit tests
  mocktail: ^0.3.0
  http_mock_adapter: ^0.3.2
  bloc_test: ^9.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
